Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket to create

Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: queue-demo-user

  IAMUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: queue-demo-user-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
      Users:
        - !Ref IAMUser

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: "*"
